### ISSUE TITLE
Lazy loading images not working properly

### ISSUE THREAD

**Issue by hg1** [iamwill123/vue-masonry-starter-pack#1]
It seems like that the combination of vue-clazy-load & vue-masonry in this example does not work as expected. All images getting loaded at once instead of loaded when scrolling into view. Can you please check it out?

**Comment by iamwill123** [comment]
@hg1 hey apologies, I have not worked on this template in a long time, I've stepped away from Vue to React. I hope you were able to resolve this. I am no longer maintaining this repo, thanks.
